/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salsafadhila
 */
public class suhu extends javax.swing.JFrame {

    /**
     * Creates new form suhu
     */
    public suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbcelcius1 = new javax.swing.JRadioButton();
        rbfahrenheit1 = new javax.swing.JRadioButton();
        rbcalvin1 = new javax.swing.JRadioButton();
        rbcelcius2 = new javax.swing.JRadioButton();
        rbfahrenheit2 = new javax.swing.JRadioButton();
        rbcalvin2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btncalculate = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel1.setText("Input");

        jLabel2.setText("From");

        jLabel3.setText("To");

        rbcelcius1.setText("celcius");

        rbfahrenheit1.setText("Fahrenheit");

        rbcalvin1.setText("Calvin");

        rbcelcius2.setText("celcius");

        rbfahrenheit2.setText("Fahrenheit");

        rbcalvin2.setText("Calvin");

        jLabel4.setText("Result");

        btncalculate.setText("calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbcalvin1)
                            .addComponent(rbfahrenheit1)
                            .addComponent(rbcelcius1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbfahrenheit2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbcelcius2)
                            .addComponent(rbcalvin2))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btncalculate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel1)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcelcius1)
                    .addComponent(rbcelcius2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfahrenheit1)
                    .addComponent(rbfahrenheit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcalvin1)
                    .addComponent(rbcalvin2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        // TODO add your handling code here:
     double Input;
     float Result = 0;
     String a;
     Input = Double.parseDouble(txtInput.getText());
     
     
     if(rbcelcius1.isSelected() && rbcelcius2.isSelected())
         Result =  (float) Input;
         a = String.valueOf(Result);
         txtResult.setText(a);
     if(rbcelcius1.isSelected() && rbfahrenheit2.isSelected())
         Result =  (float) (Input * 9 / 5 + 32);
         a = String.valueOf(Result);
         txtResult.setText(a);
     if(rbcelcius1.isSelected() && rbcalvin2.isSelected())
         Result =  (float) (Input + 273);
         a = String.valueOf(Result);
         txtResult.setText(a);
         
     if(rbfahrenheit1.isSelected() && rbcelcius2.isSelected())
         Result =  (float) (Input - 32) * 5 / 9 ;
         a = String.valueOf(Result);
         txtResult.setText(a);
     if(rbfahrenheit1.isSelected() && rbfahrenheit2.isSelected())
         Result =  (float) Input;
         a = String.valueOf(Result);
         txtResult.setText(a);
     if(rbfahrenheit1.isSelected() && rbcalvin2.isSelected())
         Result =  (float) ((Input - 32) * 5 / 9 + 273) ;
         a = String.valueOf(Result);
         txtResult.setText(a);
         
     if(rbcalvin1.isSelected() && rbcelcius2.isSelected())
         Result =  (float) (Input - 273) ;
         a = String.valueOf(Result);
         txtResult.setText(a);
     if(rbcalvin1.isSelected() && rbfahrenheit2.isSelected())
         Result =  (float) ((Input - 273) * 9 / 5 + 32);
         a = String.valueOf(Result);
         txtResult.setText(a);
     if(rbcalvin1.isSelected() && rbcalvin2.isSelected())
         Result =  (float) Input;
         a = String.valueOf(Result);
         txtResult.setText(a);   

    }//GEN-LAST:event_btncalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalculate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JRadioButton rbcalvin1;
    private javax.swing.JRadioButton rbcalvin2;
    private javax.swing.JRadioButton rbcelcius1;
    private javax.swing.JRadioButton rbcelcius2;
    private javax.swing.JRadioButton rbfahrenheit1;
    private javax.swing.JRadioButton rbfahrenheit2;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
